#!/bin/env bash

# Bash Script that transfers a file from our client to server:

# Checking the conditions for argument passed
if [ "$4" ]; then
     scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
     # Return Usage message 
     echo "Usage: 0-transfer_file  PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
     exit 1
fi
