#!/usr/bin/env bash
#Task: Install Nginx Web Server into a remote server.
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw status
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
