#!/usr/bin/env bash
#Task: Install Nginx Web Server into a remote server.

apt-get  update -y

apt-get install nginx -y

ufw allow "Nginx HTTP"

echo 'Hello World!' > /var/www/html/index.html

service nginx restart