#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
mkdir -p /etc/nginx/html/index.html
echo "301 Moved Permanently" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/josephakaro;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
