#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
echo "Alx Africa" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://github.com/josephakaro;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
