#!/usr/bin/env bash
# Update the system and install Nginx
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get install -y nginx

# Create a configuration file for the custom header
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/0-custom-http-header.conf

# Restart Nginx to apply changes
sudo service nginx restart
