#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a new Nginx configuration file
sudo tee /etc/nginx/sites-available/custom-http-response-header <<EOF
server {
    listen 80;
    server_name web-01;

    location / {
        add_header X-Served-By $hostname;
        ...
    }
}

server {
    listen 80;
    server_name web-02;

    location / {
        add_header X-Served-By $hostname;
        ...
    }
}
EOF

# Create a symbolic link to the new configuration file
sudo ln -s /etc/nginx/sites-available/custom-http-response-header /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo nginx -s quit

sudo nginx
