#!/bin/bash

# Update the system
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend web_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 422357-web-01  34.207.188.65:80 check
    server 422357-web-02 54.197.130.119:80 check
EOF

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart

