#!/bin/bash

# Update package index
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Install HAProxy
sudo apt install haproxy -y

# Configure HAProxy
haproxy_conf="/etc/haproxy/haproxy.cfg"
sudo cp "$haproxy_conf" "$haproxy_conf.bak"  # Backup the original configuration file

# Edit the HAProxy configuration file
sudo tee "$haproxy_conf" > /dev/null <<EOT
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 422357-web-01 54.144.156.100:80 check
    server 422357-web-02 34.227.91.46:80 check
EOT

# Enable HAProxy to be managed via init script
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy