#!/usr/bin/env bash
# apache 2 debuging
sudo apt-get update
sudo apt-get install apache2
sudo service apache2 start
sudo chown root:root /var/www/html/index.html
sudo chmod -R 755 /var/www/html/
echo "Hello Holberton" | sudo tee /var/www/html/index.html